//
//  GallaryCarsArticleListView.swift
//  Cars
//
//  Created by RMP on 27/10/1447 AH.
//

import SwiftUI

struct GallaryCarsArticleListView: View {
    
    @State var article1 = [
        
        GallaryCar(mainTitle: "* Toyota Tacoma Generations: Which One Is Best? (According To Owners)", mainArticle: "When the Toyota Tacoma first rolled onto American roads in 1995, it quickly made an indelible impression on automotive history and soon built a fiercely loyal following. You didn't just drive a Tacoma — you joined a club of owners who valued capability, durability, and understated cool. The beloved Taco is the kind of pickup that's as comfortable hauling gear to a remote campsite as it is sitting in a mall parking lot covered in trail dust. From the first generation's bulletproof reliability to the fourth generation's high tech off-road prowess, the Tacoma has consistently stood out in the midsize-truck segment. In 2025, the Tacoma even became the first midsize pickup ever to win Truck of Texas. It's also reportedly one of the top 10 slowest-depreciating vehicles of 2025. The fourth-gen Tacoma that launched in 2024 brought substantial upgrades to the pickup truck's powertrain, safety, tech, and suspension. It also sparked high markups at Toyota dealerships. However, even though it's the most advanced Tacoma yet, the newest edition is still earning its stripes. So with diehard fans loyal to each individual Toyota Tacoma generation, we hit the forums, YouTube reviews, and auto blogs to settle the question — which Tacoma generation is the best?", mainImage: "tacoma1", gallaryImageAndArticle: [
        
            SubGallaryCar(title: "What do drivers look for in a good Tacoma?", article: "Since debuting in the nineties, the Toyota Tacoma has transcended midsize-truck status to become an enthusiast icon. Taco forums aren't just message boards for proud Toyota Tacoma owners — they're full-blown digital communities where owners debate, share upgrades, and defend their favorite generation. Ask one of these groups what makes a good Tacoma, and the answers echo familiar themes and threads — reliability, off-road capability, and long-term dependability. My previous two vehicles was a 2007 Tacoma PreRunner RWD. Never let me down and I was the 2nd owner at 180,000 miles,  claimed 4G Taco member Jim_TRD_Offroad. Sold it when I got to 245,000 miles. Never let me down. It was a great Taco. It was fast and simple tech. Of course, not every era is perfect. Some third generation owners on Tacoma World still gripe about its sticky engine/transmission combo. Nevertheless, each generation of the pickup truck is unique, and virtually all have inspired their own enthusiast forum, like Tacoma 3G and 4G Taco, are filled with fans fawning over the Tacoma like it's an X-Wing. Judging from the online feedback of Tacoma owners and auto critics, the best Tacoma generation must merge workhorse reliability, off-road chops, and comfortable everyday drivability while avoiding transmission issues –- and without losing its unmistakable Taco soul.", image: "tacoma2"),
            
            SubGallaryCar(title: "The first generation Tacoma punched above its weight", article: "The compact truck wars of the '90s were fierce, but the first-generation Toyota Tacoma (1995 to 2004) came out swinging. Amidst fierce competition, Toyota established a legacy of reliability and performance that continues to influence the Tacoma line today. Replacing the Hilux-based Toyota Pickup, the Tacoma introduced a sturdier, reinforced frame and improved ride quality. The design shift catered to an evolving market, where pickups were being used for daily driving rather than solely as workhorses. The introduction of the 3.4L V6 engine in 1995 punched up the driving power to 190 horsepower and 220 lb-ft of torque. Enthusiasts and owners often highlight the Tacoma's exceptional power and reliability, with reports calling it one of the top vehicles that will make it to 250,000 miles and beyond. The model's durable construction has contributed to its strong resale value, with a low-mileage 2004 Tacoma fetching $45,000 at a Bring a Trailer auction in 2023. The first-gen Tacoma was also designed with off-road enthusiasts in mind. The debut of the TRD Off-Road package in 1998 equipped models with cool new features, like a locking rear differential. Undeniably, the first-generation Toyota Tacoma set a high standard in the compact pickup segment. All things considered, the first generation does have the potential to be Toyota's best edition of the Tacoma.", image: "tacoma3"),
            
            SubGallaryCar(title: "The second generation overhaul bulked-up the Taco", article: "Despite facing some early troubles — like a suspension prone to fracturing that prompted a recall – the Toyota Tacoma got bigger and more powerful in its second generation, which ran from 2005 to 2015. The update blurred the line between midsize and full-size, appealing to a broader range of drivers, from daily commuters to off-road enthusiasts. The 2005 overhaul included a new 4.0L V6, stronger towing, and tech upgrades, turning the Tacoma from a popular truck into a full-blown lifestyle icon. The 4.0L V6 was the star, producing 245 horsepower and 282 lb-ft of torque. That power let 4WD models tow up to 6,500 pounds while maintaining solid fuel economy. Owners on forums often highlight the V6's durability, noting these engines handle highway miles and off-road abuse with minimal issues. In 2021, a 2006 Toyota Tacoma X-Runner stirred debate among Taco enthusiasts when it went up for sale online for nearly $26,000. The second generation also expanded options with Regular, Access, and Double Cab configurations, featuring a wider, taller cab that made the truck look even bigger and cooler. On the road, even the four-wheel-drive models ride far better than before, noted a MotorTrend review of the 2005 Tacoma, which also observed that the V-6 is smooth and quiet and has a surprising amount of punch.", image: "tacoma4"),
            
            SubGallaryCar(title: "The third generation Tacoma went high-tech and off-road-ready", article: "Toyota rolled out the third generation of the Tacoma in 2016 with a serious redesign, making the pickup sleeker, more tech-savvy, and fully off-road-ready. A 3.5L Atkinson-cycle V6 produced 278 hp and paired with a six-speed automatic, giving the Tacoma more power and pull. TRD Off-Road and Pro trims boosted capabilities, with the 2020 TRD Pro lifted even more and featuring what Toyota promised was one of its most advanced off-road suspension systems. The third-generation Tacoma won countless accolades through 2023 and remains a favorite among off-road purists. When it debuted, one first-drive review of the 2016 Tacoma by Cars.com noted that while This new engine has 1 less pound-feet of torque, it feels much stronger than the bigger 4.0-liter V-6 it's replacing. Despite minor complaints about fuel efficiency and transmission issues, many owners praise this era. My Tacoma has the 3.5-liter 6-cylinder engine option and I have never been in a situation where I have wished I had more power, wrote Trail Tacoma after a year with a 2019 Off-Road 4X4 Tacoma. In long-term testing of the 2016 TRD Off-Road done by Edmunds editors lauded its durability, crawl-control stability, and responsiveness on dirt roads. Unfortunately, there were a few caveats to all of the awesomeness from the third-gen Tacoma. Fuel economy was lacking, and owners reported transmission troubles. While not perfect, the third-gen Tacoma is hard to beat as a midsize pickup. Overall, its off-road performance and unshakable reliability make the third generation a strong contender for Toyota's best-ever generation of the Tacoma.", image: "tacoma5"),
            
            SubGallaryCar(title: "4th-Gen Tacoma named first midsize pickup to win Truck of Texas", article: "The 2024 Toyota Tacoma didn't just evolve — it reinvented itself from bumper to bumper. Now built on Toyota's global TNGA-F platform (shared with the Tundra), the fourth-generation Tacoma is the most comprehensive overhaul in the truck's 30-year history. Every major component – chassis, powertrain, suspension, and interior — has been updated to bring the midsize legend into a competitive new era. Gone is the old 3.5L V6. In its place, Toyota introduced a 278-hp 2.4L turbocharged four-cylinder with 317 lb-ft of torque, or the 326-hp i-Force Max hybrid pushing 465 lb-ft — a massive torque leap. Business Insider noted that the engine had a surprisingly throaty rumble and is one of the better-sounding four-cylinder engines on the market. Most trims now feature a coil-spring multi-link rear suspension, replacing the decades-old leaf setup. When Jalopnik got the chance to take the 2024 Toyota Tacoma Trailhunter off-roading over steep inclines and sharp rocks, our reviewer found that the trim proved itself as an immensely adept off-roader. Beyond that, the 2025 Tacoma became the first-ever midsize pickup to win Truck of Texas. Is that enough to name the fourth generation the best Tacoma ever?", image: "tacoma6"),
            
            SubGallaryCar(title: "Reliability, performance, and real-world ownership", article: "Among Toyota Tacoma loyalists, the verdict is almost universal. The first generation's 3.4-liter V6 and old-school simplicity created a truck so durable that many still run strong after 250,000-plus miles. The second and third generations brought more comfort, capability, and tech, but also a few quirks. There was frame rust in the second generation, as well as faulty axles and sticky transmissions in the third generation, yet both continue to rank among the most dependable midsize pickups on the road. My '99 4Runner had 205,000 before my daughter rolled it, said one first-gen owner on a TacomaWorld thread discussing how many miles a Tacoma will last. Only a mere 215k miles on my '09 and she still runs like new, added ToyoTaco25 in another thread discussing Tacoma reliability. Keep the oil changed, tires rotated regularly, and keep on drivin. Despite some early transmission concerns with the 2024 Tacoma, the fourth-generation Tacoma's new turbocharged engine is a major leap in ride quality and performance. Edmunds rates the 2024 Tacoma a four out of five for reliability, and on the Tacoma4G forum, new owners echo that sentiment: One year of owning my 2024 Sport 4x4! I am happy to report zero mechanical/electrical issues with the truck.", image: "tacoma7"),
            
            SubGallaryCar(title: "Verdict: The best Tacoma generation (according to owners)", article: "The 2024 Tacoma marks a major turning point for Toyota's legendary midsize pickup. After nearly three decades of updates, the fourth generation is not just new; according to owners and auto critics, it's a notable improvement.Gone is the aging V6, replaced by Toyota's i-Force 2.4-liter turbocharged four-cylinder and optional hybrid powertrain, both delivering more torque and smoother performance. The new coil-spring rear suspension vastly improves ride quality. Combined with an upgraded frame, new eight-speed transmission, and cutting-edge interior tech, the fourth-gen Tacoma is more modern yet hasn't lost its rugged Taco soul. Longtime owners agree. The new MY24 Taco has less rear tire droop with the coil spring suspension vs a stock 3rd gen leaf spring, said one owner, who praised the TRD off-road suspension on TacomaWorld. Real-world testing backs the accolades. In a Tacoma Lifestyle YouTube comparison, longtime Tacoma owners called the fourth-gen 10 times better than their previous trucks. The influencers praised the new truck's refined handling, upgraded tech, and the long-awaited elimination of third-gen gear-hunting issues. As Car and Driver wrote, it's better than before in virtually every way.", image: "tacoma8"),
            
            SubGallaryCar(title: "Tacoma's Million-Mile Club", article: "Few trucks have proven their endurance quite like the Toyota Tacoma. The legend began when a first-generation Tacoma made headlines in 2017 after being driven nearly a million miles. Not to be outdone, a second-generation 2008 Tacoma shattered that milestone in 2021 by racking up 1.52 million miles. It was a feat so impressive that Toyota engineers brought the truck back for study. Despite the astronomical mileage, the Tacoma's frame was still solid and the transmission had never been replaced. I have a 2008 TRD off road 4.0 V6 with 350,000 miles on it all original, no major repairs, reported an owner in 2022 on a Rokslide forum thread discussing Gen 2 Tacoma reliability. I run it hard everywhere, and it spends at least 1/4 of its time hunting rough country ... I would buy one again for sure. It's never stranded me and I've driven it every day since 2008. That longevity helps explain the Toyota Tacoma's impressive resale value. Now, with the fourth-generation Tacoma, Toyota has re-engineered the mighty Taco for a long-lasting future. The 2024 Tacoma adds a boxed steel frame and powerful engines for greater torque, driving power, and long-term durability. If history is any indication, it won't be long before the newest Tacoma joins — and maybe leads — the million-mile club.", image: "tacoma9")
            
        
        ], articleLink: "https://www.jalopnik.com/2050846/best-toyota-tacoma-generations/", tag: 0)
    
    
    ]
    
    @State var article2 = [
        
        GallaryCar(mainTitle: "* 5 Toyotas With The Longest Production Runs.", mainArticle: "The Toyota lineup has many familiar names like Highlander and Prius, but some models have been around longer than others. In fact, two have been in production and sold in the U.S. for over half a century (that's the Land Cruiser and Corolla, if you're curious). Meanwhile, the Camry and 4Runner have been on the market since the 1980s. Even the Tacoma gets called out for its longevity, having been in Toyota showrooms for over three decades. The breakdown of these models appears below, with the qualifier that this article covers models sold in the U.S. (the same nameplates available elsewhere may have different production runs). In addition, we didn't look at continuous production cycles, just the total number of model years for each vehicle (including 2026). This distinction matters only for the Land Cruiser, which left Toyota's lineup after 2022 and returned for 2024. Production of the other models hasn't been interrupted. It's worth highlighting (let's call it an honorable mention) that the RAV4, Toyota's perennial best-seller, didn't make the top-five cutoff. While this model helped launch the compact SUV craze when it debuted for the 1996 model year, its 31-year manufacturing run isn't enough to earn senior status. The same can be said for the Sienna (29 years), Avalon (28 years), and Tundra (27 years).", mainImage: "article2", gallaryImageAndArticle: [
        
            SubGallaryCar(title: "Toyota Tacoma (1995-2026: 32 model years)", article: "Strictly looking at the Tacoma nameplate, this truck's story starts in 1995, when Toyota first added the label to its line of pickups. However, the company's history with trucks in the U.S. dates back to the 1960s. The first generation launched with a pair of four-cylinder engines that never exceeded 150 horsepower, but a 3.4-liter V6 powerplant later became available, increasing output to 190 ponies. The second-gen Tacoma, which debuted for 2005, morphed into a larger, more powerful machine. V6 power, via a 4.0-l Following an if it ain't broke, don't fix it philosophy, the Tacoma soldiered on until it was redesigned for the 2016 model year. The changeover brought a new V6 engine making 278 horsepower, while still offering an inline-four powerplant for buyers looking for efficiency over brawn. Along the way, the Tacoma earned a reputation for solid reliability, which has translated into strong resale value. The truck consistently ranks among the top vehicles for lowest depreciation. The current Tacoma, the fourth generation, hit showrooms for 2024, ditching six cylinders for a standard turbocharged inline-four engine. In its continued drive toward electrification, Toyota added a hybrid option, cranking output to a robust 326 horsepower. Mercifully, the Tacoma is still available with a six-speed manual gearbox, albeit with only a few configurations.", image: "article2-3"),
            
            SubGallaryCar(title: "Toyota 4Runner (1984-2026: 43 model years)", article: "The 4Runner traces its roots to the Toyota Hilux pickup, which dates back over half a century in the U.S. Yet, it took over two decades for Toyota to adapt the truck into an SUV that's been part of the company's model range for over 40 years. The first generation showed its pickup roots with the absence of a second row and a removable fiberglass top. In 1990, the second-generation 4Runner debuted with a more refined presence and a solid roof across the entire top. The base 2.4-liter four-cylinder engine offered a modest 116 horsepower, while the optional 3.0-liter V6 increased output to 150 horsepower. A 1996 redesign introduced the third-generation 4Runner with a new 3.4-liter V6 that produced 183 horsepower. At the same time, Toyota added more trims, including the upscale Limited with leather upholstery. While the automaker softened the exterior of the fourth-generation 4Runner, it didn't shortchange the engine bay. The 2003 launch featured a standard 4.0-liter V6 engine and an optional 4.7-liter V8 powerplant. The fifth-generation 4Runner was produced from 2010 through 2024, without a V8 under the hood. The body-on-frame architecture remained, while a 2020 update added standard driver-assist technologies, including automatic emergency braking. The sixth generation launched for 2025, sharing a platform with the Tacoma, Land Cruiser, and other Toyota products. As with the Tacoma, power comes from the same turbocharged four-cylinder and optional hybrid units.", image: "article2-4"),
            
            SubGallaryCar(title: "Toyota Camry (1983-2026: 44 model years)", article: "The Toyota Camry is like ants at a summer picnic — they're everywhere. Even in today's SUV- and truck-heavy marketplace, this stalwart sedan continues to rank high in sales. In 2024, it was the best-selling passenger car (non-SUV or truck) in the U.S., with Toyota moving over 300,000 units. The Camry launched for 1983, when popular vehicles of the era included the Oldsmobile Cutlass, Ford Escort, and Chevrolet Cavalier. More than 40 years later, only the Camry is still being produced. The first Toyota Camry featured a squared-off exterior — very typical of '80s design — and sold 50,000 examples in its initial year. Back when automakers had shorter product life cycles, the next version rolled out for 1987 with somewhat softer lines, while the third-generation Camry (1992-1996) adopted a more bulbous look. While the sedan has been the traditional body style for the Camry, Toyota did offer coupe and station wagon variants during these earlier years. 1997 marked another redesign. This first year of the fourth generation helped push total Camry production total in the U.S. to two million units. By 2000, another one million Camrys were built. 2007 marked the release of the sixth generation, which broke new ground with the first Camry Hybrid. This version featured a continuously variable transmission (CVT) and an EPA fuel economy rating of 40 mpg in the city, a 65% improvement over the base four cylinder's city rating. The launch of the ninth-generation Camry for 2025 marked the model becoming a hybrid-only offering.", image: "article2-5"),
            
            SubGallaryCar(title: "Toyota Corolla (1969-2026: 58 model years)", article: "Unsurprisingly, the world's most popular car has been in production for well over half a century. The Toyota Corolla debuted in the U.S. for the 1969 model year, a well-timed entrance before the first energy crisis in 1973. By today's standards, the first Corolla was modest, offering a 1.1-liter four-cylinder engine making 60 horsepower. In comparison, the base six-cylinder engine in a 1969 Chevrolet Corvair produced 95 horsepower. The Corolla helped spur competition from Detroit, including the Ford Pinto and Chevrolet Vega. Each successive generation brought refinements, especially under the hood, with increased displacements and a switch to overhead cam architecture in the 1980s. In addition, Toyota introduced more variants beyond the bread-and-butter sedan, with performance versions like the mid-1980s AE86 popularized by the Initial D anime series. This period also saw another significant change: the transition to a front-wheel-drive layout. After 12 generations, today's Corolla has come a long way, but it still anchors the automaker's U.S. passenger car lineup. Buyers can opt for a hybrid edition that can be outfitted with all-wheel drive. Toyota has also kept the five-door body style alive with the Corolla Hatchback and the 300-horsepower GR Corolla.", image: "article2-6"),
            
            
            SubGallaryCar(title: "Land Cruiser (1958-2021, 2024-2026: 67 model years)", article: "The Land Cruiser has been available in the U.S. since 1958, starting as the 20 Series, a small SUV more akin to a Jeep CJ. Another 2 years later, Toyota rolled out the 40 Series (FJ40) with a 125-horsepower inline-six-cylinder engine. In 1967, the automaker added the larger Land Cruiser 55 Series to the lineup with wagon-like styling that more closely resembled modern SUVs. The 1980s were transformative for the Land Cruiser. The 55 Series was replaced with the more refined 60 Series, and the smaller FJ40 was dropped. This would lead to the Land Cruiser 80 Series for the 1991 model year. In addition to an upgraded suspension and a more versatile four-wheel-drive system, leather upholstery was available, giving the Land Cruiser an upscale touch. The 80 Series underpinned the first Lexus LX 450. The Land Cruiser graduated to V8 power with the introduction of the 100 Series for 1998, helping cement the SUV's flagship status in the Toyota lineup. A decade later, the more upscale 200 Series debuted with a 381-horsepower V8 under the hood. This generation would continue through 2021, the final year of this behemoth utility in the U.S. An all-new five-seat Land Cruiser appeared for 2024 with a turbocharged 2.4-liter four-cylinder hybrid engine and styling cues from the original 60 Series. The new version slots between the 4Runner and the Sequoia.", image: "article2-7")
        
        
        ], articleLink: "https://www.jalopnik.com/2056602/toyota-models-with-longest-production-runs/", tag: 1)
        
    ]
    
    @State var article3 = [
        
        GallaryCar(mainTitle: "* These Toyota Models Can Last Over 200,000 Miles, According To Consumer Reports", mainArticle: "In the last few decades, technical advancements in the automotive industry have meant that you can expect the average car to last at least 200,000 miles, provided you keep up with the specified service intervals. Nothing guarantees your car will prove to be durable, but it is possible to limit risk by choosing a model that gives you trouble-free driving — and that's where Consumer Reports (CR) comes in. The nonprofit consumer market research company ranked 2025 models that are expected to last up to 200,000 miles based on its surveys. The list was dominated by Toyota vehicles, which made up eight of the 12 picks. This is not too surprising. Although unreliable Toyotas do exist, the Japanese automakers cars are known for being dependable. We've only made room for the top five Toyota models here, meaning you won't find some of the big names you might anticipate on our list, such as the 2025 Toyota RAV4, Tundra, and Sienna, even though all three made the original CR list. Aside from Toyota, Honda had two vehicles on the list, while Ford and Chevrolet had one each.", mainImage: "article3", gallaryImageAndArticle: [
        
            
            SubGallaryCar(title: "2025 Toyota Tacoma", article: "Reliability has long been the Toyota Tacoma's bread and butter, so much so that you could have pretty much picked any model year for this list. Evidence abounds of Tacomas surpassing 200,000 miles. Of particular note is the 2008 Tacoma that was featured on the ToyotaJeff Reviews YouTube channel — it racked up over 1.6 million miles on the odometer. As for the 2025 Tacoma, it came in seventh place out of the top 12 longest-lasting cars as rated by Consumer Reports, with its reliability rated as being well above-average. The midsized pickup truck also earned an above-average rating in owner satisfaction surveys, with CR testers noting its off-road performance and user-friendly controls as the strongest points. As the Tacoma was redesigned from the ground up for the 2024 model year, it offers a design that's still fresh, along with modern technology and three reasonably efficient powertrain options based on a turbocharged 2.4-liter four-cylinder. In base form, the engine makes 228 horsepower while returning up to 23 miles per gallon combined. Toyota also offers a more powerful version of the engine with 270 or 278 horses, depending on whether it's mated to the available six-speed manual or standard eight-speed automatic. Then there's a hybrid variant known as the i-Force Max. It pairs the 2.4-liter four-cylinder engine with an electric motor for a combined 326 hp and 465 lb-ft of torque.", image: "article3-1"),
            
            SubGallaryCar(title: "2025 Toyota Highlander", article: "Compared with the Tacoma, the current fourth-generation Toyota Highlander has been around long enough to have gained significant mechanical and technical updates as part of a midlife refresh for the 2023 model year. The most significant update is a new 2.4-liter turbocharged inline-four engine that's torquier, more efficient, and brings a 50% reduction in CO2 emissions compared with the old 3.5-liter V6 engine. Despite these updates, the Highlander's usual reliability factor hasn't changed, even if the 2025 Consumer Reports survey rates it as average. The crossover SUV came sixth out of the top 12, which suggests it's slightly less troublesome than the Tacoma. Owner satisfaction reviews are above-average, and the crossover SUV receives praise from CR testers for its comfortable ride and generous second-row space. Even with these virtues, though, the 2025 Highlander is far from perfect. Consumer Reports says the new turbo-four feels noticeably less refined than the previous V6, and the infotainment system falls somewhat short on ease of use. Additionally, third-row space is said to be a little on the small side compared to other midsized three-row SUVs.", image: "article3-2"),
            
            SubGallaryCar(title: "2025 Toyota Corolla", article: "It may not be the most satisfying car to own, but the Toyota Corolla can't be ignored when it comes to reliability. The compact car has proven to be an extremely dependable ally through several generations and will happily run for hundreds of thousands of miles without significant issues as long as it is well maintained. As a matter of fact, there are people getting over 500,000 miles out of their Corollas, which tells you everything you need to know about how durable they can be. Meanwhile, the 2025 Corolla scored impressively well in CR's reliability survey. Only one recall has been issued since its launch and owners seem to be enjoying many fault-free miles, as evidenced by the lack of complaints on the National Highway Traffic Safety Administration (NHTSA) website. Even if something does go wrong, many will find the repair costs to be very manageable, as the average annual repair cost for a Toyota Corolla is $362, according to RepairPal. This means it costs $79 less than you'd pay to fix the average Toyota model, which should be easier to stomach.", image: "article3-3"),
            
            SubGallaryCar(title: "2025 Toyota Prius", article: "The Prius is the car that brought self-charging hybrid technology to the masses following its debut in 1997, and it has been excelling in terms of reliability since. The second- and fourth-generation Prius models, in particular, are known for being well-built and dependable, and examples like this properly driven and maintained second-gen Prius with over 500,000 miles are proof of how long these cars can last. The current fifth-generation Prius appears to have drawn inspiration from its most reliable predecessors. The 2025 model came in fourth in Consumer Reports' list of the longest-lasting cars, after securing above-average points in the organization's reliability and owner satisfaction surveys. Of course, you also know you're getting a lot more than just exceptional reliability with the fifth-generation Prius, as it is one of the modern self-charging hybrids that can get you 50 mpg or more. In its most efficient form, the Prius claims an average economy figure of 57 mpg.", image: "article3-4"),
            
            SubGallaryCar(title: "2025 Toyota Camry", article: "Finally, the Toyota Camry is top of the Consumer Reports durability league for 2025, having finished in first place ahead of the Honda CR-V. It won't come as a surprise to many, seeing as the Camry, like many other Toyotas, has a very strong history of bulletproof reliability. The 2025 model earned well above-average ratings for reliability and owner satisfaction. Most trims are also noticeably more efficient now that the Toyota Camry is only available as a full hybrid. The EPA-estimated fuel economy figures range from 44 to 51 mpg. Previously, nonhybrid versions of the Camry returned between 25 and 32 mpg in mixed driving. So now that it delivers fuel-sipping mpg figures across the board, the Camry should be generally more affordable to run. According to CarEdge data, fuel cost ($4,530) constitutes only 13% of the total running cost for the Toyota Camry, which amounts to $34,297 over five years. This makes fueling the second-lowest ongoing cost for the midsized car, after maintenance (4%).", image: "article3-5")
        
        
        
        ], articleLink: "https://www.jalopnik.com/2067608/toyota-models-that-last-200k-miles-consumer-reports/", tag: 2)
        
    ]
    
    
    @State var article4 = [
        
        GallaryCar(mainTitle: "* 5 Cars That Are Expected To Last Like A Honda Accord", mainArticle: "The Honda Accord has been synonymous with safe, practical, reliable, and fuel-efficient driving since debuting as a three-door hatchback in 1976. Despite competing in a waning segment of a market now dominated by pickups and SUVs, the Accord is a safe bet for a sleek, four-door family sedan that's expected to last many miles with periodic servicing. According to the 2025 Longest-Lasting Study by automotive research website iSeeCars, Honda ranks third among the top 10 longest-lasting brands, with the Accord coming in ninth in the list of passenger cars with the highest chances of reaching 250,000-plus miles. The Accord has an 8.8% chance of lasting over 250,000 miles, more than 3.4 times the average of other sedans. We at Jalopnik love the Accord, and we've called the existing 11th-generation Accord a family sedan done right. But there are other cars with higher percentages of reaching 250,000 miles in the iSeeCars study. We also looked at data from J.D. Power, the National Highway Traffic Safety Administration (NHTSA), and the Insurance Institute for Highway Safety (IIHS) to list five passenger cars that are expected to last like Honda's perennial family sedan.", mainImage: "article4", gallaryImageAndArticle: [
        
            SubGallaryCar(title: "Acura ILX: 10.6% chance of lasting 250,000 miles", article: "Acura axed the ILX from its North American lineup in 2022, and it all had to do with the revival of the Integra nameplate. We had a go in the Integra Type S in 2023, and we didn't stop short of calling it the perfect road car (no offense to the ILX, of course). Although Edmunds gave the 2022 ILX a 6.6 out of 10 owing to its dated features and technology, there's nothing old-fashioned about the ILX's perceived reliability and longevity. It ranks just above the Camry Hybrid in the iSeeCars study, scoring a 10.6% chance of lasting 250,000-plus miles, and is expected to last 4.1 times longer than the average car. Moreover, the 2021 Acura ILX received a 77/100 from J.D. Power, and the Acura dealership experience remains top-notch with an 83/100 score. Safety-wise, NHTSA gave the 2021 ILX a 5 out of 5 safety rating, and it garnered an IIHS Good rating in crashworthiness testing.", image: "article4-1"),
            
            
            SubGallaryCar(title: "Honda Civic: 10.9% chance of lasting 250,000 miles", article: "Honda gave Americans their first taste of the Civic in 1972. And like the Accord, it won the hearts of many for its practical, durable, and reliable nature. We called the 2025 Civic Hatchback Hybrid the best economy car for the money, while the rowdy Civic Type R is a blast from the past, albeit better, more potent, and still fun to drive. The Civic in any flavor not only guarantees a safe, pleasant run, but its promise of reliability is hard to ignore. The Civic, too, ranks higher than the Accord in the longest-lasting passenger car study. It has a 10.9% chance of lasting 250,000-plus miles and is expected to last 4.2 times the average. Furthermore, the 2025 Civic received a consumer-verified 85/100 from J.D. Power, with the quality and reliability score at 84/100 and the resale value at 90/100. The Civic is also a beacon for safety, with the IIHS giving the 2025 Civic Hatchback a Top Safety Pick+ rating. Moreover, the 2022 Civic sedan received a 5 out of 5 overall safety rating from NHTSA.", image: "article4-2"),
            
            
            SubGallaryCar(title: "Toyota Prius: 12.2% chance of lasting 250,000 miles", article: "The Toyota Prius was among the first commercially available hybrid-electric cars, and every generation since 1997 has been stellar in reliability. Therefore, it's unsurprising that the Prius is third on the list of the longest-lasting passenger cars with a 12.2% chance of making it over 250,000 miles. We're still reeling from the redesigned Prius' hi-tech shape and rejuvenated performance, and earning an industry-wide reputation for problem-free motoring is just icing on the cake. J.D. Power agrees, too, since the next-gen Prius garnered 78/100 from verified owners and 75/100 in the quality and durability criteria. It also doesn't hurt that the Prius has a 5 out of 5 overall NHTSA safety rating and is an IIHS Top Safety Pick+ for the 2025 and 2026 model years. The market is not short on choices if you want a family sedan that can last like a Honda Accord, but the common denominator here is to stick to brands renowned for durability if you want to drive, more than fix, cars.", image: "article4-3"),
            
            SubGallaryCar(title: "Toyota Avalon: 18.9% chance of lasting 250,000 miles", article: "Unsurprisingly, Japanese auto giant Toyota ranks first among the car brands that make the longest-lasting cars, followed closely by Lexus and Honda. The folks at iSeeCars.com have estimated that Toyota vehicles last up to 3.7 times the average and have a 17.8% chance of making it over 250,000 miles. However, the Toyota Avalon stands above and beyond other family sedans in durability and perceived reliability. J.D. Power gave the 2022 Avalon a consumer-verified 83 out of 100 overall, while it scores 91/100 in quality and reliability. Furthermore, the Avalon was second in the longest-lasting cars study, earning an 18.9% chance of making it beyond 250,000 miles.  And the 2019 Toyota Avalon is an IIHS Top Safety Pick+, while the 2021 model received a 5 out of 5 NHTSA safety rating. Sure, we called the Avalon America's stupidest car not so long ago, but it doesn't mean it's not a great car for the right person or family. Toyota axed the Avalon for the 2022 model year, so it's a slightly better choice than the Accord if all you want is a turnkey solution for daily motoring. Ditto for the Avalon Hybrid, which is expected to last 3.8 times longer than average.", image: "article4-4"),
            
            
            SubGallaryCar(title: "Lexus IS: 27.5% chance of lasting 250,000 miles", article: "It would be wrong to make a list of cars that can last longer than the Accord without mentioning the Lexus IS, a car that can last up to 10.6 times the average and has a 27.5% chance of lasting 250,000 miles in the iSeeCars.com study. We wouldn't mind owning a 2025 Lexus IS 500 Ultimate Edition and its drool-worthy naturally-aspirated V8, and we can live with the tight second row and rather compromised practicality just to hear that engine rumble. With that said, the Camry and Accord are roomier than the Lexus, but no Toyota or Honda sedan is available with a 472-horsepower 5.0-liter V8. And the Lexus ES Hybrid would be a better comparison to the Accord, but it ranked lower (just barely) than the Accord in the longest-lasting study. Still, J.D. Power gave the 2022 Lexus IS a consumer-verified 86/100, with the driving experience gathering the highest rating at 93/100. Meanwhile, the 2023 Lexus IS 500 received a 5 out of 5 overall safety rating from NHTSA, while the 2022 model is an IIHS Top Safety Pick+.", image: "article4-5")
        
        
        ], articleLink: "https://www.jalopnik.com/2088982/cars-that-can-last-like-honda-accord/", tag: 3)
    
    ]
    
    @State var article5 = [
        
        GallaryCar(mainTitle: "* These Are The 10 Least Expensive New Cars In America Right Now", mainArticle: "To young adults, folks raising a family, or people who are simply on a tight budget, buying a new car in their lifetime feels about as likely as winning the lottery — and hitting the Powerball seems like the only way to possibly afford one. After all, they have to deal with groceries, housing, insurance, and child care, just as a few examples. So many things cost an absurd amount of cash in the U.S., and it makes a new car (which costs about $50,000 on average nowadays) seem thoroughly unattainable. If used cars aren't in your purview and a new car is the only way, it's worth taking a look at the 10 cars listed below. They aren't ultra-luxurious, super sporty, or high-class, but they get the job done (and they're the cheapest the U.S. market has to offer right now). Of course, some of them make sacrifices in the name of affordability, but you'll find that this group of automobiles provides some diversity in terms of segment and size. For this particular list, we're counting down the 10 cheapest 2026 model year cars by their base MSRP (not including taxes and fees).", mainImage: "article5", gallaryImageAndArticle: [
        
            SubGallaryCar(title: "10. Volkswagen Jetta: $23,995", article: "A cheap German car sounds like an oxymoron — unless you're talking about the Volkswagen Jetta. With a starting price just a tick under $24,000, this compact sedan undercuts other affordable sedans like the Mazda 3 and even the Honda Civic. Of course, it isn't quite as highly rated as those two, but saving a thousand bucks might be worth the Jetta's poorer fun-factor. Under the hood of the cheapest Jetta is VW's 158 horsepower turbocharged 1.5-liter inline-four connected to an eight-speed automatic transmission. That's good for a 0-60 mph run of 7.1 seconds, which will keep up with traffic no problem. If you can tolerate the base Jetta's somewhat frustrating eight-inch touchscreen controls, which unfortunately replaced physical HVAC knobs recently, you'll be rewarded with a passenger area that is comfortable and fairly spacious for its size. To us, one of the major pulls of the Jetta (aside from its price) is that it's the last surviving Volkswagen sedan. The larger Passat was officially dead in the U.S. by 2022, and the only other small four-door VW is the Golf, which costs about $10,000 more than the Jetta in its cheapest form. The next cheapest VW is the compact Taos SUV, which costs almost $3,000 more, and after that, every other model is more than $30,000 in base MSRP. It's also worth mentioning that the high-performance GLI version of the Jetta, with its 228 horsepower 2.0-liter turbo-four, still costs less than a Golf GTI. It even gets a six-speed manual, which is no longer available in new Golf models.", image: "article5-1"),
            
            SubGallaryCar(title: "9. Kia Seltos: $23,790", article: "Subcompact SUVs aren't normally exciting, and while the Kia Seltos isn't necessarily a standout exception to that rule, it makes a case for itself that's hard to ignore. According to Car and Driver, the Seltos ranks third in a segment of 15 or more subcompact SUVs that were tested for the 2026 model year. This puts the Seltos ahead of the offerings from big-hitters like Toyota, Honda, and Subaru. The price, of course, is a big help. Its $23,790 base MSRP is a direct target for families looking for affordable transportation, but unlike many others, that low cost isn't compensation for a lack of features and driving dynamics. All-wheel drive is standard on the base and top trim models, and it's an option on the S and EX trims that occupy the middle of its range. Additionally, the Seltos' combined fuel economy of 29 MPG (with base engine) is perfectly normal for this segment, which usually ranges from the high 20s to low 30s. Power is delivered by your choice of two engines: a 146 horsepower 2.0-liter inline-four, or a turbocharged 1.6-liter four-pot that's good for 195 horsepower. Like most base models on this list, power and torque won't be sporty by nature, but the Seltos makes up for its okay engine with exceptional ride quality and a better-than-expected interior. To top it off, the Seltos is backed by Kia's 100,000-mile/10-year power train warranty, which is a perk that isn't matched anywhere else in the market.", image: "article5-2"),
            
            SubGallaryCar(title: "8. Chevrolet Trailblazer: $23,300", article: "The Trailblazer's name goes back over two decades, and its kinfolk — the Blazer — is more than 50 years old. But the bigger Blazer is now electric, and the Trailblazer is handling the internal combustion department all on its own. As far as reliable, practical, and affordable transportation goes, the compact SUV certainly lives up to its legacy, offering decent space and a low base MSRP of $23,300. Unfortunately, the Trailblazer falls a bit short in other aspects. Despite having a tiny turbocharged 1.2-liter three-cylinder in base form, the Trailblazer's fuel economy rating (30 city/31 highway) is still just average in this segment. And because of its lack of displacement, the Trailblazer ends up suffering in output, boasting just 137 horsepower and 162 pound-feet of torque. The upgraded turbocharged 1.3-liter three-cylinder engine isn't much better, providing 155 horsepower and 174 pound-feet. You can get all-wheel drive in the Chevy, but unlike the Kia Seltos, you can't get it with the base engine. Its driving dynamics also don't inspire confidence like some of its rivals. Braking performance is decent, though when it comes to overall handling and ride quality, the Chevy is outshone by most of the others in its segment. The Trailblazer experience isn't all gloom, though. Its cargo room of 54 cubic feet (with rear seats down) is great for its small size, the interior is well-thought-out and tastefully designed, and the infotainment system is user-friendly. In the end, you do get what you pay for, but you don't get much more.", image: "article5-3"),
            
            SubGallaryCar(title: "7. Toyota Corolla: $22,925", article: "Most cars and SUVs fluctuate in popularity year by year, but the Toyota Corolla is an exception, having remained as one of the most dependable cars on the road. Even amongst such quality company as those Camry and Acura, there really isn't a more popular vehicle than the Corolla. It even managed to sell more than 50 million units, and part of that success is thanks to its price. For 2026, the Corolla's commitment to cheap transportation continues with a base MSRP of $22,925, making it the seventh-cheapest new car available in the U.S. One of the standout concepts behind this Corolla is its number of trims, as well as their cost. The Corolla lineup features 10 different trims across both gas and hybrid power train options, but all are situated within just $6,000 of each other (not including the GR variant). This gives customers the agency to decide on spending more money for the features they'll want without draining their bank account. The base 168 horsepower 2.0-liter inline-four is actually the more powerful of the two options, as the hybrid power train delivers just 134 horsepower (albeit with better fuel economy). A continuously variable transmission (CVT) is the only gearbox you can have, but if you want upgrades, higher trims come with fun stuff like sportier suspension, some added leather bits, bigger wheels, ambient interior lighting, a 10.5-inch infotainment screen (as opposed to the eight-inch base option), and other small changes.", image: "article5-4"),
            
            SubGallaryCar(title: "6. Hyundai Elantra: $22,625", article: "The Elantra covers many bases throughout its range. It comes with nine trims and four different power trains, and five different transmissions. At the bare minimum, you can have it for an incredibly competitive price of $22,625. The entry-level engine is a simple 2.0-liter inline-four producing 147 horsepower, and it's paired exclusively with a CVT. Inside, a standard eight-inch infotainment screen is present along with wireless Apple CarPlay and Android Auto. Also, because Hyundai and Kia share a parent, the 100,000-mile/10-year power train warranty is available for the Elantra. Moving down the trim levels, buyers also have the option for a hybrid 1.6-liter four-cylinder power train (136 horsepower), a turbocharged 1.6-liter four-pot in the N-Line trim (201 horsepower), and the high-performance variant, the Elantra N, with a turbocharged 2.0-liter inline-four capable of 286 horsepower. In that same order, the standard transmissions are a six-speed dual-clutch, a seven-speed dual-clutch, and either a six-speed manual or eight-speed dual-clutch for the N (in addition to the CVT for the base car). On the road, most accounts show that the lower-trimmed Elantras aren't as capable as one might hope, while the turbocharged models more than make up for it with great all-around dynamics. Unfortunately, to get to those fun models like the N-Line or Elantra N, you'd have to spend anywhere from $7,000 to $13,000 more, respectively.", image: "article5-5"),
            
            SubGallaryCar(title: "5. Nissan Sentra: $22,600", article: "The 2026 Nissan Sentra has lost much of the nameplate's soul. It's now in its ninth generation, surviving in a world that doesn't care much for compact sedans in general. Even so, the newest Sentra does its best to emit small glimmers of its former glory. Meaningful differentiating factors between trims are gone. Of course, you can get upgraded tech and additional features if you spring for the SR instead of the base S trim, but nothing changes the car's fundamental character. In previous generations, customers got at least two different engine options with varying levels of power, suspension tuning, and their choice of a manual or automatic transmission. In 2026, the Sentra loses all of that, sticking to just one engine and transmission – a 149 horsepower 2.0-liter inline-four driven through a CVT. But it all makes perfect sense; the market for the Sentra is slowly dying anyway. Small SUVs and EVs are poised to continue growing in popularity, and if Nissan wants to stay in business (which hasn't been easy recently), then it needs to focus more on other models. Granted, despite its unenthusiastic demeanor, the Sentra's ride quality is good enough, and the new tech (like the huge standard 12.3-inch infotainment screen) is seriously competitive in this segment. At the end of the day, the Sentra is transportation, and when the entry fee is just $22,600, you can't expect much more.", image: "article5-6"),
            
            SubGallaryCar(title: "4. Nissan Kicks: $22,430", article: "The Nissan Kicks is a relatively recent addition to the brand's lineup. Debuting for North America in 2018, it filled the hole that the oddball Nissan Juke left after its U.S. discontinuation the same year. The Juke was actually quite successful for most of its life, but in the second half of the 2010s, poor sales finally caught up with it. The Kicks is now in the second year of its second generation, which brought a wide array of changes. It was made bigger, received all-wheel drive options, restyled the interior and exterior, and most importantly, replaced the old 1.6-liter engine in favor of a new 2.0-liter, 141 horsepower inline-four. Handling was also improved, as was cargo space, which now offers 59 cubic feet of storage with the rear seats folded down (or 50 cubic feet with AWD option). For 2026, not much is different from the inaugural second-gen specs we've just listed — and its demerits remain mostly the same, too. The Kicks' base infotainment touchscreen is a tiny seven inches, requiring a trim upgrade to get the larger 12.3-inch unit. Additionally, while the 2.0-liter engine is better than the first-gen car, it doesn't inspire much confidence in acceleration. Plus, its limited warranty of three years/36,000 miles and power train warranty of five years/60,000 miles are just average in the current industry. But the price is the factor that makes this package feel worth it. While it used to cost less than $20,000, the current $22,430 base MSRP still makes the Kicks a top contender for affordability in its segment.", image: "article5-7"),
            
            
            SubGallaryCar(title: "3. Kia K4: $22,290", article: "Akin to the Corolla, the compact Kia K4 spreads out its large number of trim levels (eight in total) across a span of just around $6,000. Aside from that attractive trim spread, there are other things to like at first glance — such as the exterior. The K4 has undeniably sleek lines and a sporty silhouette that shines in both hatchback and sedan body styles. Inside, Apple CarPlay and Android Auto are standard, as well as a 12.3-inch digital infotainment screen, which is usually reserved for higher trims at this price point. The flip side, however, is that the base engine doesn't back up its good looks and great standard features. It's a 2.0-liter inline-four that's good for only 147 horsepower, all connected to a CVT. Models with the 2.0-liter are subjected to an average torsion bar rear suspension setup that limits driving engagement, but once again, better trims aren't too far away. The GT-Line and GT-Line Turbo receive a multi-link suspension, and the Turbo in particular gets a more powerful 190 horsepower turbocharged 1.6-liter inline-four, which is mated to an eight-speed automatic transmission. And if nothing else, the 100,000-mile/10-year warranty, five-star National Highway Traffic Safety Administration safety rating, and $22,290 base price should warrant some consideration for the K4.", image: "article5-8"),
            
            SubGallaryCar(title: "2. Chevrolet Trax: $21,700", article: "We liked the 2024 Chevrolet Trax a lot, and that positivity hasn't died down for 2026. Car and Driver has the subcompact SUV ranked first in its segment and features it on its 10Best list, and MotorTrend quipped that it rewrites the book on affordable motoring, which is high praise for a nameplate that most folks probably wouldn't immediately recognize. Regardless, the Trax provides a package that checks more boxes while costing less than virtually its entire competition. The SUV costs $21,700 in its base trim, making it the second-most affordable vehicle you can buy in America. From there, the Trax does well to balance practicality and driving feel, sporting a nimble and tactile suspension while housing 54 cubic feet of storage with the rear seats folded. Then we get to the cockpit, which is spacious and features digital displays that are tilted towards the driver. The screen in question is a standard eight-inch infotainment display, which is decent for this price range and segment, though customers can upgrade to an 11-inch setup in higher trims. The biggest issue with the Trax is its puny 137 horsepower turbocharged 1.2-liter three-cylinder and the lack of any all-wheel drive availability. But even then, the lack of variety is slightly made up for by the use of a traditional six-speed automatic transmission instead of the typical-for-this-segment CVT.", image: "article5-9"),
            
            SubGallaryCar(title: "1. Hyundai Venue: $20,550", article: "The Chevy Trax might be a petite SUV, only weighing around 3,000 pounds, but the Hyundai Venue is an order of magnitude smaller. Coming in at just about 2,600 pounds, it's a modern SUV that weighs less than a 2026 Toyota GR86. As you might guess, it's not going to fit a ton of stuff, and this is a bare-bones model through and through. But before you judge it, you should hear what the cheapest car in the entire U.S. market has to offer. Hyundai chose to prioritize passenger room over cargo space, and as a result, seating comfort is respectable — although buyers can only fit 32 cubic feet of stuff in the back (around 20 cubic feet fewer than something like the Trax). Also inside is the infotainment setup, which includes an eight-inch screen with Apple CarPlay and Android Auto as standard. The sole available power train is a 1.6-liter inline-four that pumps out a furious 121 horsepower and is mated exclusively to a CVT. In other words, you aren't going to be swimming through freeway traffic in this thing, but in-town commutes won't be an issue. The philosophy behind the Venue is one of necessity. If you're someone with the ability to finance $20,000 and you need basic transportation, this model is a fine choice. It's a consumer-forward product that is affordable (in this expensive economy) and doesn't pretend to be anything other than an econobox.", image: "article5-10")
        
        
        ], articleLink: "https://www.jalopnik.com/2100671/least-expensive-new-cars-usa/", tag: 4)
        
    ]
    
    
    @State var article6 = [
        
        GallaryCar(mainTitle: "* Need Raw Performance? These 9 Cars Have The Most Horsepower You Can Buy In 2026", mainArticle: "We've talked before about how much horsepower you really need, but this list isn't that. We're not here to talk about the right amount of power or the best driving experience in 2026. This list is about the most horsepower, full stop. Just the gratuitous raw power output with no consideration made for literally anything else — not driving feel, not exhaust note, not handling, not even fun. We're talking pure bragging rights on the dyno, or more realistically, a factory spec sheet that will never be tested outside of an internet forum. But we did draw exactly one line in the sand. Because this is a list aiming Oh, and one other thing. If a car only hits its big number with some sort of launch control mode or overboost or some other peak power shenanigan, that's fair game. Power is power, especially in this context.", mainImage: "article6", gallaryImageAndArticle: [
        
            
            SubGallaryCar(title: "Taycan 4S Black Edition: 590 horsepower", article: "If you're already wincing at the realization that a list like this might be nothing but EVs, spoiler alert: it's not. But at the same time, Porsche power is not known for coming cheap, and while you can get to the big numbers elsewhere in the brand lineup without electrification, you aren't getting there for less than $150,000. An entry-level Taycan will bring you just over 400 horsepower, while a Turbo GT model (at over $240,000) surpasses 1,000. But sitting right there in between so what power and way too much money is the 590 horsepower Taycan 4S Black Edition for $141,000. It's not going to crack the 2-second barrier like the Turbo GT, but it does get you the upgraded Performance Battery Pack, and that's enough to earn a spot on this list without having to compromise on comfort or refinement. There are more dynamic Porsche driving experiences available for under our price threshold, but you're not going to find one with this much power under the hood ... err, engine bay. Battery pack. Ugh, you know what we mean.", image: "article6-1"),
            
            
            SubGallaryCar(title: "Chevrolet Corvette E-Ray: 655 horsepower", article: "The Corvette E-Ray is Chevrolet's more American alternative to Porsche's 911 Turbo S, which you're not going to find on this list. That's because, despite boasting slightly more horsepower than the E-Ray, you're going to pay an eye-popping $270,300 starting price for the privilege. Alternatively, the E-Ray continues the Corvette tradition of democratizing power and performance, taking supercar styling and design to the masses with 655 horsepower for $108,600. The fact that this thing even exists feels like a display of confidence from Chevy. On top of bringing its core demographic along for the ride with a wildly successful shift from the iconic front-engine design into a mid-engine layout with the C8, the brand went even further by introducing electrification with the all-wheel drive E-Ray. Interestingly, while the E-Ray has been well-received, few fans seem blown away by the electric side of it, as it doesn't do much to improve gas mileage and has minimal range with the combustion power train switched off. Still, it'll help you get all that horsepower out of the driveway before waking up the neighborhood with an early morning cold start, so there's that.", image: "article6-2"),
            
            
            SubGallaryCar(title: "Cadillac CT5-V Blackwing: 668 horsepower", article: "Welcome to the first entry on this list that brings you the beefy horsepower you crave the old-fashioned way. Cadillac's Blackwing cars are arguably the last combustion-powered sedans that matter, and you can get your hands on one high-powered example for less than a hundred grand. With 668 horsepower for $98,900, the CT5-V Blackwing is the kind of package that we'd honestly like to see more of on this list. It's a luxury sports sedan in the truest sense. As impressive as all that is, there's another aspect that makes it even more interesting: It's a manual. It's the only manual you're going to find in a modern V8 sedan, and this just might be the last year you can buy it that way – so go ahead and vote with your dollars if you're in a position to do so. We may or may not get a continued reprieve from the end of the era as manufacturers navigate a loosened regulatory environment. Still, all signs point to the CT5-V Blackwing being your last chance for a manual-powered beast like that, whether 2026 is the last year for this configuration or not.", image: "article6-3"),
            
            SubGallaryCar(title: "Audi S e-tron GT: 670 horsepower", article: "Despite the S and GT sprinkled into the vehicle's name, the Audi S e-tron GT is the entry level to the lineup. This means that your $127,700 MSRP nets you 670 horsepower, enough to get you from zero to 60 mph in 3.3 seconds. It's exceptionally quick, and yet it has all of the comfy amenities you'd expect from an electric Audi. At its core, though, it's pretty much a slightly cheaper and more comfortable Taycan. If you're cross-shopping against the Taycan Black Edition that opened this list, you'll get 80 more horsepower in the bargain. While the more expensive performance variants of the car can boast being the fastest, most powerful production Audis of all time, this one is certainly no slouch. And as the only all-electric Audi that isn't an SUV, it's the only one from the manufacturer that you're going to find on this list.", image: "article6-4"),
            
            
            SubGallaryCar(title: "Dodge Charger Daytona Scat Pack: 670 horsepower", article: "With 670 horsepower and a base price of $73,985, the Dodge Charger Daytona Scat Pack gets you into the high horsepower game for significantly less money than anything else on our list. On one hand, it's an EV that makes for a convincing muscle car cosplay. On the other hand, when you mash the gas pedal (sorry, accelerator pedal), it's going to leave some internal combustion romanticism behind in light of the 3.3 second zero-to-60 time and a quarter-mile time of under 12 seconds. However you feel about it, Dodge has indeed ​​declared the Scat Pack the world's quickest muscle car. Even though that's based on its own definition of what muscle car even means anymore, we have to concede that if anyone gets to decide the issue, it's probably the guys who are still out there making Hellcats. Though we'll also point out that if engine sounds are a big part of an experience like this for you personally, the Daytona Scat Pack leans pretty hard into the theater of synthetic noise that's audible both inside the car and out. For better or for worse, folks will definitely know you're coming.", image: "article6-5"),
            
            
            SubGallaryCar(title: "Chevrolet Corvette Z06: 670 horsepower", article: "The E-Ray wasn't the only Corvette to slip under this list's price cap. For an MSRP of $120,300, you can get not just a gas-powered Corvette, but a Z06 making 670 horsepower. E-Ray aside, you could certainly also get pretty far down in the weeds weighing the difference between the Stingray and the Z06, but ultimately, the comparison ends when you get to how the Stingray doesn't even crack 500 horsepower from the factory. On top of being a horsepower bargain, perhaps more than anything else on this list, the Z06 is also a performance bargain. Road & Track used words like astonishing and more special than cars that cost three times as much. Car and Driver called it a value world-beater that effectively took pages from higher-end competitors like Porsche and Ferrari. Honestly, it's so good at so many things above and beyond our raw horsepower premise that it almost makes us question whether it should be on this list at all.", image: "article6-6"),
            
            SubGallaryCar(title: "BMW M5: 717 horsepower", article: "Plenty would argue that the BMW M5 invented the sports sedan segment. Today, though, people continue to debate whether recent modern versions have lost their way. Since the M5's weight has been criticized for generations, you could certainly make the case that BMW has engineered some of the sport out of its sport sedan. But you don't have to take a side on that debate to acknowledge that we're still talking about something that delivers an incredible 717 horsepower out of the box for $123,300. The model is also all-wheel drive with an eight-speed automatic, and it weighs more than 5,000 pounds – all facts that you will find amusingly difficult to locate on BMW's product page for the M5. (It's a plug-in hybrid, too, which the brand acknowledges with less coaxing.) You can call it progress or you can call it sacrilege, but you can't call it underpowered. If you insist on internal combustion, this is also the point of the list where you can go no further. It's all electric from here.", image: "article6-7"),
            
            
            SubGallaryCar(title: "Lucid Air Grand Touring: 819 horsepower", article: "We've made our way to the obscenely powerful electric car portion of our list. And, just to get this out of the way, the Lucid Air Grand Touring might be the greatest EV ever sold. It's fantastic at many things, and when it comes to raw power, it stretches close to topping this list with 819 horsepower and an MSRP of $114,900. At this trim, second only to the Lucid Air Sapphire (that'll run you more than $100,000 more), you'll get from zero to 60 in three seconds flat. Assuming you're not doing that over and over, you can also get up to 480 miles of range. You don't need to step up to the preposterous power of the Sapphire to see the Air as the ultimate example of what electrification means for cars: tons of power with no compromise needed. With the Air, you can set the cruise control and make your way silently down the highway as calmly as comfortably as any everyday GT. It's only when you unleash all that power that you'll suddenly find yourself accelerating faster than a McLaren F1 – with no regard for the fact that you're also in a well-appointed luxury car. Even if you're a gas-powered purist, it might just be time to get used to this sort of thing.", image: "article6-8"),
            
            SubGallaryCar(title: "Tesla Model S Plaid: 1,020 horsepower", article: "Tesla was really the first company to unabashedly lean into hypercar horsepower numbers from an otherwise reasonable sedan. Even the Plaid nomenclature is itself a bit of deliberately over-the-top whimsy, a reference to going plaid at super speeds in the movie Spaceballs. Cute packaging aside, the Model S Plaid lands firmly atop our mountain of value-priced power with 1,020 horsepower for $109,490. In addition to giving you the higher-output tri-motor, the Plaid package will also get you some exterior styling, improved aerodynamics, and sports seats. You might notice that there are a couple of extras missing from what you might expect for a higher-priced vehicle trim you've upgraded into four-figure horsepower territory — namely, brakes and tires. For that, it turns out that Tesla wants another $15,000 for its Model S Plaid Performance Package, though this will indeed get you upgraded carbon-ceramic rotors with forged-aluminum wheels and performance Goodyears. We're not saying that you necessarily need all that for the occasional straight-line party trick, but it might not be the worst idea. Regardless, we promised a list full of raw horsepower at under $150,000 and made no promises about stopping or turning, so Tesla takes the crown here.", image: "article6-9")
        
        ], articleLink: "https://www.jalopnik.com/2120958/cars-with-most-horsepower-2026/", tag: 5)
    
    ]
    
    @State var articleData: GallaryCar = GallaryCar(mainTitle: "", mainArticle: "", mainImage: "", gallaryImageAndArticle: [], articleLink: "", tag: 0)
    
    @Environment(\.dismiss) var dismiss
    
    @State var showGallaryDetailsView: Bool = false
    
    @State var addingToFavorites = false
    
    var body: some View {
        
        
        
        NavigationView {
            
            List {
                
                ForEach(article1) { brand in
                    
                    Button {
                        
                        
                        addingToFavorites = false
                        articleData = brand
                        showGallaryDetailsView = true
                        
                        
                        
                    } label: {
                        
                        VStack(alignment: .leading) {
                            Text(brand.mainTitle).font(.headline).tint(Color(uiColor: UIColor(.primary))).lineLimit(nil).fixedSize(horizontal: false, vertical: true)
                            Image(brand.mainImage).resizable().aspectRatio(contentMode: .fit).frame(minWidth: 50, maxWidth: .infinity, minHeight: 200).cornerRadius(20)
                            
                        }
                        
                    }
                    
                }
                
                
                ForEach(article2) { brand in
                    
                    Button {
                        
                        addingToFavorites = false
                        articleData = brand
                        showGallaryDetailsView = true
                        
                        
                        
                    } label: {
                        
                        VStack(alignment: .leading) {
                            Text(brand.mainTitle).font(.headline).tint(Color(uiColor: UIColor(.primary))).fixedSize(horizontal: false, vertical: true)
                            Image(brand.mainImage).resizable().aspectRatio(contentMode: .fit).frame(minWidth: 50, maxWidth: .infinity, minHeight: 200).cornerRadius(20)
                            
                        }
                        
                    }
                    
                }
                
                ForEach(article3) { brand in
                    
                    Button {
                        
                        addingToFavorites = false
                        articleData = brand
                        showGallaryDetailsView = true
                        
                        
                    } label: {
                        
                        VStack(alignment: .leading) {
                            Text(brand.mainTitle).font(.headline).tint(Color(uiColor: UIColor(.primary))).fixedSize(horizontal: false, vertical: true)
                            Image(brand.mainImage).resizable().aspectRatio(contentMode: .fit).frame(minWidth: 50, maxWidth: .infinity, minHeight: 200).cornerRadius(20)
                            
                        }
                        
                    }
                    
                }
                
                
                ForEach(article4) { brand in
                    
                    Button {
                        
                        addingToFavorites = false
                        articleData = brand
                        showGallaryDetailsView = true
                        
                        
                    } label: {
                        
                        VStack(alignment: .leading) {
                            Text(brand.mainTitle).font(.headline).tint(Color(uiColor: UIColor(.primary))).fixedSize(horizontal: false, vertical: true)
                            Image(brand.mainImage).resizable().aspectRatio(contentMode: .fit).frame(minWidth: 50, maxWidth: .infinity, minHeight: 200).cornerRadius(20)
                            
                        }
                        
                    }
                    
                }
                
                ForEach(article5) { brand in
                    
                    Button {
                        
                        addingToFavorites = false
                        articleData = brand
                        showGallaryDetailsView = true
                        
                        
                    } label: {
                        
                        VStack(alignment: .leading) {
                            Text(brand.mainTitle).font(.headline).tint(Color(uiColor: UIColor(.primary))).fixedSize(horizontal: false, vertical: true)
                            Image(brand.mainImage).resizable().aspectRatio(contentMode: .fit).frame(minWidth: 50, maxWidth: .infinity, minHeight: 200).cornerRadius(20)
                            
                        }
                        
                    }
                    
                }
                
                ForEach(article6) { brand in
                    
                    Button {
                        
                        addingToFavorites = false
                        articleData = brand
                        showGallaryDetailsView = true
                        
                        
                    } label: {
                        
                        VStack(alignment: .leading) {
                            Text(brand.mainTitle).font(.headline).tint(Color(uiColor: UIColor(.primary))).fixedSize(horizontal: false, vertical: true)
                            
                            Image(brand.mainImage).resizable().aspectRatio(contentMode: .fit).frame(minWidth: 50, maxWidth: .infinity, minHeight: 200).cornerRadius(20)
                            
                        }
                        
                    }
                    
                }
                

            }.toolbar(content: {
                
                ToolbarItem(placement: .navigationBarLeading) {
                    
                    Button {
                        
                        dismiss.callAsFunction()
                        
                    } label: {
                        
                        Image(systemName: "chevron.down")
                        
                    }

                    
                }
                
            }).navigationTitle("Articles").listStyle(.grouped)
            
        }.fullScreenCover(isPresented: $showGallaryDetailsView) {
            GallaryDetailsView(article: $articleData, addingToFavorites: $addingToFavorites)
        }
        
    }
}

struct GallaryCarsArticleListView_Previews: PreviewProvider {
    static var previews: some View {
        GallaryCarsArticleListView()
    }
}
